import React from 'react';

export function About() {
  return (
    <>
    <header className="mx-auto max-w-3xl px-4 pt-8 text-center sm:px-6 sm:pt-12">
      <h1 className="text-3xl font-bold tracking-tight sm:text-4xl">About</h1>
    </header>
    <main className="mx-auto max-w-3xl space-y-10 px-4 py-8 sm:px-6 sm:py-12">
      <p className="text-lg leading-relaxed text-neutral-600">
	Traditional note apps force you to spend more time organizing folders than actually thinking. Liquid Notes is a voice-first knowledge base where an on-device AI automatically transcribes, organizes, and links your ideas together in real time. Instead of searching through static files, your database adapts dynamically to your queries, surfacing hidden connections and letting your thoughts branch naturally.
      </p>

      <dl className="grid gap-4 sm:grid-cols-2">
	<div className="rounded-2xl bg-white p-5 shadow-sm ring-1 ring-black/5 sm:p-6">
	  <dt className="font-semibold text-sky-700">
	    Drop <span className="font-normal text-neutral-500">· The Input</span>
	  </dt>
	  <dd className="mt-2 leading-relaxed text-neutral-600">
	    A single raw audio clip, quick thought, or brief note. It is the liquid seed that waters the system.
	  </dd>
	</div>

	<div className="rounded-2xl bg-white p-5 shadow-sm ring-1 ring-black/5 sm:p-6">
	  <dt className="font-semibold text-sky-700">
	    Roots <span className="font-normal text-neutral-500">· The Hidden Layer</span>
	  </dt>
	  <dd className="mt-2 leading-relaxed text-neutral-600">
	    The background semantic connections, tags, and shared contexts. Roots work automatically beneath the surface to anchor related Drops together without manual folder creation.
	  </dd>
	</div>

	<div className="rounded-2xl bg-white p-5 shadow-sm ring-1 ring-black/5 sm:p-6">
	  <dt className="font-semibold text-sky-700">
    	    Tree <span className="font-normal text-neutral-500">· The Synthesis</span>
    	  </dt>
    	  <dd className="mt-2 leading-relaxed text-neutral-600">
    	    A dynamic, structured workspace or long-form document generated by AI by stitching together
    	    multiple Drops along a specific line of inquiry.
    	  </dd>
    	</div>

    	<div className="rounded-2xl bg-white p-5 shadow-sm ring-1 ring-black/5 sm:p-6">
    	  <dt className="font-semibold text-sky-700">
    	    Forest <span className="font-normal text-neutral-500">· The Knowledge Base</span>
    	  </dt>
    	  <dd className="mt-2 leading-relaxed text-neutral-600">
    	    The entire visual graph and searchable database of everything you've ever spoken or recorded.
    	  </dd>
    	</div>
      </dl>
    </main>
    </>
  );
}
